### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Jay-Miles**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)

### CODE REVIEW

**Review by nadia31415 — CHANGES_REQUESTED** [review]
As an ad hoc script, I understand the need for the file ids.
If the plan is to automate, you may want to  remove these ids, pass input files as arguments and add some exception handling to ensure what you grep out is in the correct format before finding unique variants 

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-:-NhWmCww9X5YnDh9JEWw:b-axblla)* status: all files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @Jay-Miles)

___
*[`files/s1_f1_tso_projects` line 1 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRL7ABDtTEVt2JB71W:-NhRL7ABDtTEVt2JB71X:bi87wml) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/files/s1_f1_tso_projects#L1)):*
> ```
> project-GVj5ZF84f2F1K3668FFg0gzq : 002_230525_A01303_0202_BH7YK5DRX3_TSO500 (CONTRIBUTE)
> ```

It might be worth checking if this file needs removing (i.e project ids to production data)
___
*[`src/s1_get_cases_and_files.sh` line 15 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRNWH0Ayx4yAHva28b:-NhRNWH0Ayx4yAHva28c:b-ay941k) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L15)):*
> ```Shell
> printf "\nListing affected projects\n\n"
> 
> dx find projects --name "002_23052*_TSO500" > "$file_1"  # May
> ```

Does this command work as expected for May (would the current code not skip 1st May)? The number of integers for the other months is 4 i.e 2306, 2308 etc... 
___
*[`src/s2_unarchive_files.sh` line 25 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRQ8Mp7eRIxdkB9pmH:-NhRQ8Mp7eRIxdkB9pmI:b-vqk44l) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s2_unarchive_files.sh#L25)):*
> ```Shell
> while read -r file_id; do
> 
>     dx unarchive "$file_id" -y
> ```

Did this loop through any unexpected errors?  In the past, I've had `dx unarchive` throwing errors (assuming you're doing multiple files in a loop). 
I find adding a`sleep 5` after the unarchive command resolves this (can be tweaked to sleep 2)  in between each iteration
___
*[`src/s3_compare_files_single.sh` line 99 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRX5LO0wQR1dj2Py5X:-NhRX5LO0wQR1dj2Py5Y:b-7w9hka) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s3_compare_files_single.sh#L99)):*
> ```Shell
> 
>                     # get vcf transcripts, gnomad, and clinvar info
>                     vcf_trscpt_p=$(grep -Po '(?<=;CSQ_HGVSp=)(.*?)(?=:p.)' <<< "$vcf_var")
> ```

After grepping the transcripts and annotation info, do you think its useful to add error handling to ensure transcripts etc.. are in correct format?
Also, did you explore whether using bcftools to query the info (or format) field for CSQ_HGVSp then grepping the substring also works instead of relying on grep alone?  
___
*[`src/s5_find_unique_vars.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRbYxT5l22_GEk6OnK:-NhRbYxT5l22_GEk6OnL:b6s78py) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s5_find_unique_vars.py#L19)):*
> ```Python
>     variant = f"{chrom}:{pos}:{ref}:{alt}:{tsv_trscpt}"
> 
>     if variant not in variants.keys():
> ```

This method is really nice, using keys in the variant dictionary.

Just wondered if searching and storing for unique variants separately would be faster so you don't have to go through the whole dictionary in this loop? Would that save time? 
___
*[`src/s5_find_unique_vars.py` line 60 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhR_vRQBoFRluY3aEnx:-NhR_vRQBoFRluY3aEny:b-auf0gp) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s5_find_unique_vars.py#L60)):*
> ```Python
> with open('files/s5_f1_unique_mismatch_variants', 'w') as writer:
>     writer.write("chrom\tpos\tref\talt\tgene\ttsv_pdot\ttsv_trscpt\ttsv_cons\tvcf_pdot\tvcf_trscpt_p\tvcf_trscpt_c\tvcf_gnomad_g\tvcf_gnomad_e\tvcf_clinvar\tcase_count\tcases\n")
> ```

Could you add a small comment for what the loop is for?

**Comment by Jay-Miles** [comment]
*[`src/s1_get_cases_and_files.sh` line 15 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRNWH0Ayx4yAHva28b:-NhWyPWX0r--OBc-27bh:bl3f7h8) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L15)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Does this command work as expected for May (would the current code not skip 1st May)? The number of integers for the other months is 4 i.e 2306, 2308 etc...
</blockquote></details>

The version of the Helios manual which used VEP v107 was released on 22 May 2023, so we don't want to pull in any projects before that date. However thinking about it more, you're right, this code is still problematic because it would exclude projects from the 30/31 of May. Will rethink.

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: all files reviewed, 8 unresolved discussions (waiting on @Jay-Miles and @nadia31415)

___
*[`src/s1_get_cases_and_files.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-2NXD9oLDTaiQ-VzG:-Ni-2NXD9oLDTaiQ-VzH:bjlh9ej) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L11)):*
> ```Shell
> file_6="files/s1_f6_final_output"
> 
> ## LIST ALL AFFECTED PROJECTS (59 projects)
> ```

can see you listed per time but can make it easier by doing it by using the "created date" dnanexus parameter to set the date. Can check the other parameters by using "dx find projects -h" e.g



_Code snippet:_
```Shell
dx find projects --name "002*_TSO500" --created-after="2023-05-01"
```
___
*[`src/s1_get_cases_and_files.sh` line 68 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-3T9N3UC0P1FzSRvl:-Ni-3T9N3UC0P1FzSRvm:b-u911pp) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L68)):*
> ```Shell
> done < "$file_2"
> 
> # remove duplicate records, sort by case id, get list of unique dna cases
> ```

why remove duplicate records and if there are duplicate records, which ones to you keep?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: all files reviewed, 11 unresolved discussions (waiting on @Jay-Miles and @nadia31415)

___
*[`src/s2_unarchive_files.sh` line 3 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-3hpt6DXNpEskNST6:-Ni-3hpt6DXNpEskNST7:bq8afnp) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s2_unarchive_files.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> 762 cases, each with two files (tsv and vcf)
> ```

comment?
___
*[`src/s3_compare_files_single.sh` line 79 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-5OrY6QyOejgmR8NY:-Ni-5OrZ3V3yMkrtei5T:b-9iqvsz) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s3_compare_files_single.sh#L79)):*
> ```Shell
>     tsv_pdot="${no_br//\(/}"
> 
>     if [[ -n "${tsv_pdot// /}" ]]; then
> ```

if tsv_pdot is not blank? if so pls comment :)
___
*[`src/s3_compare_files_single.sh` line 107 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-62_p59f-NA84BG71:-Ni-62_p59f-NA84BG72:b-r66onc) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s3_compare_files_single.sh#L107)):*
> ```Shell
>                     vcf_clnsig=$(grep -Po '(?<=;CSQ_ClinVar_CLNSIG=)(.*?)(?=;)' <<< "$vcf_var")
> 
>                     # if tsv and vcf variants affect the same transcript
> ```

why? if the p.notation differs and the transcripts arent the same (e.g different versions of the same transcript) will you still log it ? Also you are checking the transcript used for the vcf p.notation OR c.notation match the tsv p.notation, so the second condition isnt needed it seems.

**Review by Jay-Miles — COMMENTED** [review]
Hi both,

Thanks for your reviews. I thought about what you both said regarding the file structure and passing arguments, and I've restructured the code to try and improve that. The main changes are:

- reduced the number of scripts
- no intermediate output files
- different approach to identifying TSV and VCF files, no longer any issue with duplicates

There are still a couple of things which need fixing, so I'm continuing to work on the remaining comments.

Thanks
Jay

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-:-Ni-yQULBG9F22dIN9qu:b-xb5fjl)* status: 0 of 19 files reviewed, 11 unresolved discussions (waiting on @Aisha-D and @nadia31415)

___
*[`files/s1_f1_tso_projects` line 1 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRL7ABDtTEVt2JB71W:-Ni-w0DWEKqDz6jhXyfc:bo3id19) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/files/s1_f1_tso_projects#L1)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

It might be worth checking if this file needs removing (i.e project ids to production data)
</blockquote></details>

Good point - will remove.
___
*[`src/s1_get_cases_and_files.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-2NXD9oLDTaiQ-VzG:-Ni-w4MT7OQilcCaJTAf:b6rkz5j) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L11)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can see you listed per time but can make it easier by doing it by using the "created date" dnanexus parameter to set the date. Can check the other parameters by using "dx find projects -h" e.g
</blockquote></details>

Thanks - have updated to get projects within a specific timeframe.
___
*[`src/s1_get_cases_and_files.sh` line 15 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRNWH0Ayx4yAHva28b:-Ni-wDLS4pwpSQRy-GeW:b-t3xufr) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L15)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

The version of the Helios manual which used VEP v107 was released on 22 May 2023, so we don't want to pull in any projects before that date. However thinking about it more, you're right, this code is still problematic because it would exclude projects from the 30/31 of May. Will rethink.
</blockquote></details>

Fixed using --created-after and --created-before as suggested by Aisha
___
*[`src/s1_get_cases_and_files.sh` line 68 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-3T9N3UC0P1FzSRvl:-Ni-wJZgDMTqZAdAgc73:b3ncb5) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s1_get_cases_and_files.sh#L68)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

why remove duplicate records and if there are duplicate records, which ones to you keep?
</blockquote></details>

Have changed the approach to identifying files, this is no longer applicable
___
*[`src/s2_unarchive_files.sh` line 3 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-3hpt6DXNpEskNST6:-Ni-w_hN3UJ1MWxXz0EZ:b-fl9hxy) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s2_unarchive_files.sh#L3)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

comment?
</blockquote></details>

Doh. Fixed
___
*[`src/s2_unarchive_files.sh` line 25 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRQ8Mp7eRIxdkB9pmH:-Ni-wfLG1HZy28IrAegd:bvll5vr) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s2_unarchive_files.sh#L25)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Did this loop through any unexpected errors?  In the past, I've had `dx unarchive` throwing errors (assuming you're doing multiple files in a loop). 
I find adding a`sleep 5` after the unarchive command resolves this (can be tweaked to sleep 2)  in between each iteration
</blockquote></details>

I haven't had any errors yet, but I'll add this in case any crop up in future.
___
*[`src/s3_compare_files_single.sh` line 79 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-5OrY6QyOejgmR8NY:-Ni-xFLhAcYeWIQS0PZz:b-896fix) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s3_compare_files_single.sh#L79)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

if tsv_pdot is not blank? if so pls comment :)
</blockquote></details>

Done.
___
*[`src/s3_compare_files_single.sh` line 107 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-Ni-62_p59f-NA84BG71:-Ni-xUiL662OwzIUWrLL:bihnmdd) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s3_compare_files_single.sh#L107)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

why? if the p.notation differs and the transcripts arent the same (e.g different versions of the same transcript) will you still log it ? Also you are checking the transcript used for the vcf p.notation OR c.notation match the tsv p.notation, so the second condition isnt needed it seems.
</blockquote></details>

If the transcripts are different, the difference between p. notations could be valid, in which case we don't want to record it as a mismatch. You're right about transcript versions though, it might be worth adding something in to cover this. Will have a think.

Regarding the second condition, the p. notation provided in the TSV file doesn't always use the NP transcript, it sometimes uses an NM transcript, so I wanted to check that it matched at least one of the VCF transcript fields.

**Review by Jay-Miles — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: 0 of 19 files reviewed, 11 unresolved discussions (waiting on @Aisha-D and @nadia31415)

___
*[`src/s5_find_unique_vars.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRbYxT5l22_GEk6OnK:-Ni02lPx5c9meK-XKpBT:b-qcyhla) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s5_find_unique_vars.py#L19)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

This method is really nice, using keys in the variant dictionary.

Just wondered if searching and storing for unique variants separately would be faster so you don't have to go through the whole dictionary in this loop? Would that save time?
</blockquote></details>

Good idea! Thanks :)
___
*[`src/s5_find_unique_vars.py` line 60 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhR_vRQBoFRluY3aEnx:-Ni02o3Q7Y8aTJdQK5yA:b-896fix) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s5_find_unique_vars.py#L60)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Could you add a small comment for what the loop is for?
</blockquote></details>

Done.

**Review by Jay-Miles — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: 0 of 21 files reviewed, 11 unresolved discussions (waiting on @Aisha-D and @nadia31415)

___
*[`src/s3_compare_files_single.sh` line 99 at r1](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1#-NhRX5LO0wQR1dj2Py5X:-Nj7oC8L1w3qLra6bp6N:b-lnub98) ([raw file](https://github.com/eastgenomics/vep_issue_testing/blob/afd0ea55eb7dc3a653ed5bb37cee98d49049130e/src/s3_compare_files_single.sh#L99)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

After grepping the transcripts and annotation info, do you think its useful to add error handling to ensure transcripts etc.. are in correct format?
Also, did you explore whether using bcftools to query the info (or format) field for CSQ_HGVSp then grepping the substring also works instead of relying on grep alone?
</blockquote></details>

Changed the code to use bcftools instead of grep - you're right, that was more efficient.

**Review by nadia31415 — COMMENTED** [review]
> Reviewed 14 of 19 files at r2, 1 of 5 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: all files reviewed, 8 unresolved discussions (waiting on @Aisha-D)

**Review by Aisha-D — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @nadia31415)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @nadia31415)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: all files reviewed, 3 unresolved discussions (waiting on @nadia31415)

**Review by nadia31415 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/vep_issue_testing/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jay-Miles)

**Pull request merged**
